category:
  weight: null
  drop_low: null
  late_penalty: null

assignments:
  exclude_complete_thresh: null
  exclude: null
  substitute: null

waive: null

waive_late: null

grade_thresh:
  .93: A
  .90: A-
  .87: B+
  .83: B
  .80: B-
  .77: C+
  .73: C
  .70: C-
  .67: D+
  .63: D
  .60: D-
  0: E


email_list: null